version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
  fastapi_app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./app/.env
    depends_on:
      - mongo_db
    ports:
      - "8000:80"

volumes:
  mongo: