version: '3.8'

services:
  mongo_db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mongo_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db

  mongo_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo_app
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://fastapi:password12345@mongo_db:27017/fastapi
    depends_on:
      - mongo_db

volumes:
  mongo: