version: '3'

services:
  mongo_db:
    image: mongo:latest
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
  fastapi_app:
    build:
      dockerfile: ./fastapi_mongo_app/Dockerfile
      context: .
    env_file:
      - ./fastapi_mongo_app/.env
    depends_on:
      - mongo_db
    ports:
      - "8000:8000"

volumes:
  mongo: